# permissions for end users to edit clusterversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterversion-editor-role
rules:
- apiGroups:
  - multicluster-ops.io
  resources:
  - clusterversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster-ops.io
  resources:
  - clusterversions/status
  verbs:
  - get
