# permissions for end users to view clusterversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterversion-viewer-role
rules:
- apiGroups:
  - multicluster-ops.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster-ops.io
  resources:
  - clusterversions/status
  verbs:
  - get
