name: docker-push
on:
  push:
    tags:
      - 'v*'
env:
  go-version: 1.13
  cache-version: 1
jobs:
  docker-push:
    name: Docker Push
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: taisho6339/multicluster-upgrade-operator
          tag-match: v(.*)
          tag-match-latest: false
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}